import type { Background } from '../types'

export const PHB_BACKGROUNDS: Background[] = [
  {
    index: 'acolyte',
    name: 'Acolyte',
    description: 'You have spent your life in service of a temple, learning the ways of the gods.',
    skill_proficiencies: ['insight', 'religion'],
    feature_name: 'Shelter of the Faithful',
    feature_desc: 'You command the respect of fellow worshippers and can receive free healing at temples.',
  },
  {
    index: 'charlatan',
    name: 'Charlatan',
    description: 'You have always had a talent for making people believe what you want them to believe.',
    skill_proficiencies: ['deception', 'sleight-of-hand'],
    feature_name: 'False Identity',
    feature_desc: 'You have a second identity, including documentation and established acquaintances.',
  },
  {
    index: 'criminal',
    name: 'Criminal',
    description: 'You are an experienced criminal with a history of breaking the law.',
    skill_proficiencies: ['deception', 'stealth'],
    feature_name: 'Criminal Contact',
    feature_desc: 'You have a reliable contact who acts as a liaison to a network of other criminals.',
  },
  {
    index: 'entertainer',
    name: 'Entertainer',
    description: 'You thrive in front of an audience, knowing how to captivate and inspire.',
    skill_proficiencies: ['acrobatics', 'performance'],
    feature_name: 'By Popular Demand',
    feature_desc: 'You can always find a place to perform, receiving free lodging and food in exchange.',
  },
  {
    index: 'folk-hero',
    name: 'Folk Hero',
    description: 'You come from a humble social rank, but destiny has called you to greatness.',
    skill_proficiencies: ['animal-handling', 'survival'],
    feature_name: 'Rustic Hospitality',
    feature_desc: 'Common folk will shelter you, hide you, and assist you — but not risk their lives.',
  },
  {
    index: 'guild-artisan',
    name: 'Guild Artisan',
    description: 'You are a member of an artisan guild, skilled in a particular field and business.',
    skill_proficiencies: ['insight', 'persuasion'],
    feature_name: 'Guild Membership',
    feature_desc: 'Fellow guild members provide lodging and assistance; the guild may also apply legal aid.',
  },
  {
    index: 'hermit',
    name: 'Hermit',
    description: 'You lived in seclusion for a formative part of your life, communing with nature or the divine.',
    skill_proficiencies: ['medicine', 'religion'],
    feature_name: 'Discovery',
    feature_desc: 'Your solitary isolation led you to discover a unique secret of the world.',
  },
  {
    index: 'noble',
    name: 'Noble',
    description: 'You understand wealth, power, and privilege. People are inclined to think the best of you.',
    skill_proficiencies: ['history', 'persuasion'],
    feature_name: 'Position of Privilege',
    feature_desc: 'You are welcomed in high society and commoners make every effort to accommodate you.',
  },
  {
    index: 'outlander',
    name: 'Outlander',
    description: 'You grew up in the wilds, far from civilisation and the comforts of town and technology.',
    skill_proficiencies: ['athletics', 'survival'],
    feature_name: 'Wanderer',
    feature_desc: 'You have an excellent memory for maps and terrain, and can always find food and water.',
  },
  {
    index: 'sage',
    name: 'Sage',
    description: 'You spent years learning the lore of the multiverse, poring through countless tomes.',
    skill_proficiencies: ['arcana', 'history'],
    feature_name: 'Researcher',
    feature_desc: 'When you don\'t know something, you know where and from whom to find out.',
  },
  {
    index: 'sailor',
    name: 'Sailor',
    description: 'You sailed on a seagoing vessel for years, weathering storms and fighting pirates.',
    skill_proficiencies: ['athletics', 'perception'],
    feature_name: 'Ship\'s Passage',
    feature_desc: 'You can secure free passage on sailing ships for yourself and companions.',
  },
  {
    index: 'soldier',
    name: 'Soldier',
    description: 'War has been your life for as long as you care to remember.',
    skill_proficiencies: ['athletics', 'intimidation'],
    feature_name: 'Military Rank',
    feature_desc: 'Soldiers loyal to your former military organisation recognise your rank and defer to you.',
  },
  {
    index: 'urchin',
    name: 'Urchin',
    description: 'You grew up on the streets alone, orphaned, and poor, surviving on wits and stealing.',
    skill_proficiencies: ['sleight-of-hand', 'stealth'],
    feature_name: 'City Secrets',
    feature_desc: 'You know secret passages through the city that let you move at twice the normal speed.',
  },
  {
    index: 'gladiator',
    name: 'Gladiator',
    description: 'You have made a living fighting in arenas, using skill and showmanship to entertain the crowds.',
    skill_proficiencies: ['acrobatics', 'performance'],
    feature_name: 'By Popular Demand',
    feature_desc: 'You can always find a place to perform, receiving free lodging and food in exchange.',
  },
  {
    index: 'guild-merchant',
    name: 'Guild Merchant',
    description: 'Rather than crafting goods, you buy and sell them, travelling to distant places to expand your trade.',
    skill_proficiencies: ['insight', 'persuasion'],
    feature_name: 'Guild Membership',
    feature_desc: 'Fellow guild members provide lodging and assistance; the guild may also apply legal aid.',
  },
  {
    index: 'knight',
    name: 'Knight',
    description: 'You carry a knightly title and the social standing it brings, sworn to uphold a code of chivalry.',
    skill_proficiencies: ['history', 'persuasion'],
    feature_name: 'Retainer',
    feature_desc: 'You have the service of three retainers who perform mundane tasks and remain loyal to you.',
  },
  {
    index: 'pirate',
    name: 'Pirate',
    description: 'You spent years under the sway of a dread pirate, learning what it means to live outside the law.',
    skill_proficiencies: ['athletics', 'perception'],
    feature_name: 'Bad Reputation',
    feature_desc: 'No matter where you go, people fear your reputation, letting you get away with minor offences.',
  },
  {
    index: 'spy',
    name: 'Spy',
    description: 'You are a seasoned infiltrator trained to extract information and move unseen through organisations.',
    skill_proficiencies: ['deception', 'stealth'],
    feature_name: 'Criminal Contact',
    feature_desc: 'You have a reliable contact who acts as a liaison to a network of other criminals.',
  },
]
