export const CLASS_SKILLS: Record<string, { choose: number; from: string[] }> = {
  barbarian: { choose: 2, from: ['animal-handling', 'athletics', 'intimidation', 'nature', 'perception', 'survival'] },
  bard: { choose: 3, from: ['acrobatics', 'animal-handling', 'arcana', 'athletics', 'deception', 'history', 'insight', 'intimidation', 'investigation', 'medicine', 'nature', 'perception', 'performance', 'persuasion', 'religion', 'sleight-of-hand', 'stealth', 'survival'] },
  cleric: { choose: 2, from: ['history', 'insight', 'medicine', 'persuasion', 'religion'] },
  druid: { choose: 2, from: ['arcana', 'animal-handling', 'insight', 'medicine', 'nature', 'perception', 'religion', 'survival'] },
  fighter: { choose: 2, from: ['acrobatics', 'animal-handling', 'athletics', 'history', 'insight', 'intimidation', 'perception', 'survival'] },
  monk: { choose: 2, from: ['acrobatics', 'athletics', 'history', 'insight', 'religion', 'stealth'] },
  paladin: { choose: 2, from: ['athletics', 'insight', 'intimidation', 'medicine', 'persuasion', 'religion'] },
  ranger: { choose: 3, from: ['animal-handling', 'athletics', 'insight', 'investigation', 'nature', 'perception', 'stealth', 'survival'] },
  rogue: { choose: 4, from: ['acrobatics', 'athletics', 'deception', 'insight', 'intimidation', 'investigation', 'perception', 'performance', 'persuasion', 'sleight-of-hand', 'stealth'] },
  sorcerer: { choose: 2, from: ['arcana', 'deception', 'insight', 'intimidation', 'persuasion', 'religion'] },
  warlock: { choose: 2, from: ['arcana', 'deception', 'history', 'intimidation', 'investigation', 'nature', 'religion'] },
  wizard: { choose: 2, from: ['arcana', 'history', 'insight', 'investigation', 'medicine', 'religion'] },
  artificer: { choose: 2, from: ['arcana', 'history', 'investigation', 'medicine', 'nature', 'perception', 'sleight-of-hand'] },
}

export const ALL_SKILLS = [
  { index: 'acrobatics', name: 'Acrobatics', ability: 'DEX' },
  { index: 'animal-handling', name: 'Animal Handling', ability: 'WIS' },
  { index: 'arcana', name: 'Arcana', ability: 'INT' },
  { index: 'athletics', name: 'Athletics', ability: 'STR' },
  { index: 'deception', name: 'Deception', ability: 'CHA' },
  { index: 'history', name: 'History', ability: 'INT' },
  { index: 'insight', name: 'Insight', ability: 'WIS' },
  { index: 'intimidation', name: 'Intimidation', ability: 'CHA' },
  { index: 'investigation', name: 'Investigation', ability: 'INT' },
  { index: 'medicine', name: 'Medicine', ability: 'WIS' },
  { index: 'nature', name: 'Nature', ability: 'INT' },
  { index: 'perception', name: 'Perception', ability: 'WIS' },
  { index: 'performance', name: 'Performance', ability: 'CHA' },
  { index: 'persuasion', name: 'Persuasion', ability: 'CHA' },
  { index: 'religion', name: 'Religion', ability: 'INT' },
  { index: 'sleight-of-hand', name: 'Sleight of Hand', ability: 'DEX' },
  { index: 'stealth', name: 'Stealth', ability: 'DEX' },
  { index: 'survival', name: 'Survival', ability: 'WIS' },
] as const

export const RACE_DESCRIPTIONS: Record<string, string> = {
  'dragonborn': 'Born of dragons, with an innate breath weapon and draconic resistance.',
  'dwarf': 'Bold and hardy, with mastery of stone and craft — and a legendary stubbornness.',
  'elf': 'Magical and graceful, with keen senses and centuries of accumulated wisdom.',
  'gnome': 'Small in stature but bursting with clever ideas and an enthusiasm for invention.',
  'half-elf': 'A bridge between two worlds, combining human ambition with elven grace.',
  'half-orc': 'Fierce and resilient, pushing past pain that would stop others cold.',
  'halfling': 'Lucky and nimble small folk who find comfort in simplicity and good food.',
  'human': 'Endlessly adaptable and ambitious — the most widespread race in the world.',
  'tiefling': 'Touched by infernal heritage, marked by fiendish power and devilish charm.',
}

export const CLASS_DESCRIPTIONS: Record<string, { flavor: string; hitDie: string }> = {
  'barbarian': { flavor: 'Channel primal fury into devastating rage', hitDie: 'd12' },
  'bard': { flavor: 'Weave magic through music, poetry, and performance', hitDie: 'd8' },
  'cleric': { flavor: 'Channel divine power to heal allies and smite foes', hitDie: 'd8' },
  'druid': { flavor: 'Command the forces of nature and take animal form', hitDie: 'd8' },
  'fighter': { flavor: 'Master of combat with unmatched martial versatility', hitDie: 'd10' },
  'monk': { flavor: 'Harness ki energy through discipline and martial arts', hitDie: 'd8' },
  'paladin': { flavor: 'Combine martial might with sacred oaths and holy power', hitDie: 'd10' },
  'ranger': { flavor: "Hunt and track foes with nature's blessing", hitDie: 'd10' },
  'rogue': { flavor: 'Strike from the shadows with cunning and precision', hitDie: 'd8' },
  'sorcerer': { flavor: 'Wield raw magic drawn from your very bloodline', hitDie: 'd6' },
  'warlock': { flavor: 'Draw eldritch power from a pact with a mighty being', hitDie: 'd8' },
  'wizard': { flavor: "Unlock the universe's secrets through arcane study", hitDie: 'd6' },
  'artificer': { flavor: 'Infuse objects with magic through ingenuity and invention', hitDie: 'd8' },
}
